const fragranceTypes = [
  "Eau de Parfum",
  "Eau de Toilette",
  "Eau de Cologne",
  "Extrait de Parfum",
  "Parfum",
  "Body Mist",
  "Other",
];

const fragranceBrands = [
  "Acqua di Parma",
  "Aesop",
  "Amouage",
  "Annick Goutal",
  "Armani",
  "Azzaro",
  "Balenciaga",
  "Balmain",
  "Bath & Body Works",
  "Bottega Veneta",
  "Bond No. 9",
  "Boucheron",
  "Bvlgari",
  "Burberry",
  "By Kilian",
  "Byredo",
  "Calvin Klein",
  "Carolina Herrera",
  "Cartier",
  "Celine",
  "Chanel",
  "Chloé",
  "Christian Dior",
  "Clinique",
  "Coach",
  "Comme des Garçons",
  "Creed",
  "Diesel",
  "Diptyque",
  "Dolce & Gabbana",
  "Donna Karan (DKNY)",
  "Elie Saab",
  "Elizabeth Arden",
  "Elizabeth Taylor",
  "Escada",
  "Estée Lauder",
  "Frédéric Malle",
  "Giorgio Armani",
  "Givenchy",
  "Glossier",
  "Gucci",
  "Guerlain",
  "Hermès",
  "Hugo Boss",
  "Initio Parfums Prives",
  "Issey Miyake",
  "Jean Paul Gaultier",
  "Jennifer Lopez",
  "Jimmy Choo",
  "Jo Malone",
  "John Varvatos",
  "Juicy Couture",
  "Juliette Has a Gun",
  "Katy Perry",
  "Kenzo",
  "Kilian",
  "Krigler",
  "Lacoste",
  "Lalique",
  "Lancôme",
  "Le Labo",
  "Liz Claiborne",
  "Maison Francis Kurkdjian",
  "Marc Jacobs",
  "Michael Kors",
  "Miller Harris",
  "Miu Miu",
  "Montale",
  "Montblanc",
  "Moschino",
  "Mugler",
  "Narciso Rodriguez",
  "Nautica",
  "Nina Ricci",
  "Olivier Durbano",
  "Paco Rabanne",
  "Parfums de Marly",
  "Penhaligon's",
  "Perry Ellis",
  "Philosophy",
  "Prada",
  "Ralph Lauren",
  "Revlon",
  "Roberto Cavalli",
  "Roja Parfums",
  "Salvatore Ferragamo",
  "Serge Lutens",
  "Sisley",
  "Tom Ford",
  "Tory Burch",
  "Valentino",
  "Versace",
  "Viktor & Rolf",
  "Xerjoff",
  "Yves Saint Laurent (YSL)",
  "Zara",
];

const allNotes = [
  "Agarwood (Oud)",
  "Aldehydes",
  "Almond",
  "Amber",
  "Ambergris",
  "Amberwood",
  "Amaryllis",
  "Anise",
  "Apple",
  "Apple Blossom",
  "Apricot",
  "Aqua Notes",
  "Basil",
  "Bay Leaf",
  "Benzoin",
  "Bergamot",
  "Birch Tar",
  "Black Currant",
  "Blackberry",
  "Brown Sugar",
  "Butter",
  "Butterscotch",
  "Cacao",
  "Cedarwood",
  "Chamomile",
  "Champaca",
  "Cherry",
  "Chocolate",
  "Cinnamon",
  "Cistus",
  "Clove",
  "Coconut",
  "Coffee",
  "Coriander",
  "Cream",
  "Cucumber",
  "Cumin",
  "Cyclamen",
  "Cypress",
  "Daffodil",
  "Driftwood",
  "Ebony Wood",
  "Eucalyptus",
  "Everlasting Flower",
  "Fig",
  "Fir Balsam",
  "Fir",
  "Frangipani",
  "Frankincense",
  "Freesia",
  "Galbanum",
  "Gardenia",
  "Gaiac Wood",
  "Geranium",
  "Geranium Leaf",
  "Ginger Blossom",
  "Ginger",
  "Ginseng",
  "Glossier",
  "Gourmand Notes",
  "Grapefruit Blossom",
  "Grapefruit",
  "Green Apple",
  "Green Tea",
  "Guava",
  "Hawthorn",
  "Hay",
  "Hazelnut",
  "Heliotrope",
  "Hibiscus",
  "Honeysuckle",
  "Honey",
  "Hyacinth",
  "Iris",
  "Iso E Super",
  "Ivy",
  "Jasmine",
  "Juniper Berries",
  "Kumquat",
  "Lacquer",
  "Labdanum",
  "Lemon",
  "Lemon Verbena",
  "Licorice",
  "Lime",
  "Lily of the Valley",
  "Lilac",
  "Linden Blossom",
  "Lychee",
  "Magnolia",
  "Mahogany",
  "Mango",
  "Maple",
  "Marigold",
  "Marzipan",
  "Mate",
  "Melon",
  "Milk",
  "Mimosa",
  "Mineral Notes",
  "Mint",
  "Molasses",
  "Musk",
  "Myrrh",
  "Narcissus",
  "Neroli",
  "Nutmeg",
  "Oakmoss",
  "Olive",
  "Olibanum",
  "Opoponax",
  "Orange Blossom",
  "Orange Leaf",
  "Orange",
  "Orchid",
  "Osmanthus",
  "Oregano",
  "Papaya",
  "Passionfruit",
  "Patchouli",
  "Peach",
  "Peanut",
  "Pear",
  "Pepper",
  "Peony",
  "Peru Balsam",
  "Petitgrain",
  "Pine",
  "Pineapple",
  "Pistachio",
  "Plum",
  "Plumeria",
  "Pomegranate",
  "Praline",
  "Quince",
  "Raspberry",
  "Resins",
  "Rose",
  "Rosemary",
  "Saffron",
  "Salt",
  "Sandalwood",
  "Seaweed",
  "Smoke",
  "Spikenard",
  "Star Anise",
  "Stephanotis",
  "Strawberry",
  "Styrax",
  "Suede",
  "Tangerine",
  "Tea",
  "Thyme",
  "Tobacco",
  "Tolu Balsam",
  "Tomato Leaf",
  "Tonka Bean",
  "Tuberose",
  "Tulip",
  "Vanilla Pod",
  "Vanilla",
  "Vetiver",
  "Violet Leaf",
  "Violet",
  "Walnut",
  "Water Lily",
  "Watermelon",
  "Wisteria",
  "Ylang-Ylang",
  "Yuzu",
];

export { fragranceTypes, fragranceBrands, allNotes };
